# Use an official Python runtime as a parent image
FROM python:3.9

# Set environment variables
ENV WORKDIR=/app

# Set the working directory in the container
WORKDIR $WORKDIR

# Use ADD to directly fetch the 'app' folder and 'requirements.txt' from the repository
ADD https://github.com/amitopenwriteup/cicdproject/raw/main/app/app.py $WORKDIR/app/app.py
ADD https://github.com/amitopenwriteup/cicdproject/raw/main/requirements.txt $WORKDIR/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Set up a volume for the application directory
VOLUME ["/app"]

# Expose application port
EXPOSE 5000

# Set an environment variable for runtime
ENV PYTHONUNBUFFERED=1

# Command to run the application
CMD ["python", "app/app.py"]
