# Stage 1: Builder
FROM python:3.9 AS builder

# Set environment variables
ENV WORKDIR=/app

# Set the working directory in the container
WORKDIR $WORKDIR

# Use ADD to directly fetch the 'app' folder and 'requirements.txt' from the repository
ADD https://github.com/amitopenwriteup/cicdproject/raw/main/app/app.py $WORKDIR/app/app.py
ADD https://github.com/amitopenwriteup/cicdproject/raw/main/requirements.txt $WORKDIR/requirements.txt

# Install dependencies in a temporary directory to reduce image size
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# Stage 2: Final Image (Alpine-based)
FROM python:3.9-alpine

# Set environment variables
ENV WORKDIR=/app
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR $WORKDIR

# Create a non-root user and group
RUN addgroup -g 1001 appuser && \
    adduser -u 1001 -G appuser --shell /bin/bash --home /home/appuser --disabled-password appuser

# Copy installed dependencies from the builder stage
COPY --from=builder /install /usr/local

# Copy application source code
COPY --from=builder /app /app

# Change ownership of the /app directory to the non-root user
RUN chown -R appuser:appuser /app

# Switch to non-root user
USER appuser

# Set up a volume for the application directory
VOLUME ["/app"]

# Expose application port
EXPOSE 5000

# Command to run the application
CMD ["python", "app/app.py"]
