apiVersion: v1
kind: Pod
metadata:
  name: liveness-failure
spec:
  containers:
    - name: crashing-app
      image: busybox
      args:
        - /bin/sh
        - -c
        - |
          touch /tmp/healthy; 
          echo "App is running...";
          sleep 30;  # ⏳ Wait 30 seconds
          rm -f /tmp/healthy;  
          echo "App crashed!";
          sleep 600;  # Simulate crash (keeps running but is considered unhealthy)

      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy  
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
