apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::130705418859:role/stage-nginx-sa-role
    argocd.argoproj.io/sync-wave: "1"
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
