apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-job
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
        - name: pre-sync-job
          image: alpine:latest
          command: ["sh", "-c", "echo PreSync Job"]
      restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-job
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    spec:
      containers:
        - name: post-sync-job
          image: alpine:latest
          command: ["sh", "-c", "echo PostSync Job"]
      restartPolicy: OnFailure
