apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim-2
  namespace: stage1-nginx-namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
