apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - chart: nginx
            releaseName: my-nginx
            targetRevision: 18.1.2
          - chart: apache
            releaseName: my-apache
            targetRevision: 11.2.5
  template:
    metadata:
      name: '{{releaseName}}'
    spec:
      project: stage-devseccops
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: '{{chart}}'
        targetRevision: '{{targetRevision}}'
        helm:
          releaseName: '{{releaseName}}'
      destination:
        name: arn:aws:eks:ap-south-1:130705418859:cluster/stage-devseccops-eks-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

