apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-sync
  namespace: argocd
spec:
  destination:
    name: arn:aws:eks:ap-south-1:130705418859:cluster/stage-devseccops-eks-cluster
  project: stage-devseccops
  source:
    path: nginx-sync
    repoURL: git@github.com:amitopenwriteup/nginx-argoproj.git
    targetRevision: main
    helm:
      valueFiles:
        - Values.yaml
  syncPolicy:
    automated: {}
